### ISSUE TITLE
java.lang.IllegalStateException: Could not find an appropriate constructor for com.google.cloud.bigtable.hbase1_x.BigtableConnection

### ISSUE THREAD

**Issue by yyl719133368** [googleapis/cloud-bigtable-client#2129]
Hi google,

In fact, I got the same error in another project which is work on `AWS`,I just need to change `bigtable-hbase-1.x` to `bigtable-hbase-1.x-hadoop`,and it's  work well on `AWS`.

 I have tried all version below, it's still don't work on `GCP`.

bigtable-hbase-1.x: use for standalone applications where you are in control of your dependencies.
bigtable-hbase-1.x-hadoop: use in hadoop environments.
bigtable-hbase-1.x-mapreduce: use for map/reduce utilities.
bigtable-hbase-1.x-shaded: use in environments (other than hadoop) that require older versions of protobuf, guava, etc.
bigtable-hbase-2.x: use for standalone applications where you are in control of your dependencies. This includes an HBase async client.
bigtable-hbase-2.x-hadoop: use in hadoop environments.
bigtable-hbase-2.x-shaded: use in environments (other than hadoop) that require older versions of protobuf, guava, etc.

```
2019-03-21 11:08:44,462 INFO  BigtableSession (Logger.java:info(89)) - Opening connection for projectId international-gramercy, instanceId test-manual-bt-uk, on data host bigtable.googleapis.com, admin host bigtableadmin.googleapis.com.
2019-03-21 11:08:44,464 INFO  BigtableSession (Logger.java:info(89)) - Bigtable options: BigtableOptions{dataHost=bigtable.googleapis.com, adminHost=bigtableadmin.googleapis.com, port=443, projectId=international-gramercy, instanceId=test
-manual-bt-uk, appProfileId=, userAgent=hbase-1.4.5, credentialType=SuppliedJson, dataChannelCount=12, retryOptions=RetryOptions{retriesEnabled=true, allowRetriesWithoutTimestamp=false, statusToRetryOn=[UNAVAILABLE, UNAUTHENTICATED, DEADL
INE_EXCEEDED, ABORTED], initialBackoffMillis=5, maxElapsedBackoffMillis=60000, backoffMultiplier=1.5, streamingBufferSize=60, readPartialRowTimeoutMillis=60000, maxScanTimeoutRetries=3}, bulkOptions=BulkOptions{asyncMutatorCount=2, useBul
kApi=true, bulkMaxKeyCount=125, bulkMaxRequestSize=1048576, autoflushMs=0, maxInflightRpcs=120, maxMemory=71617740, enableBulkMutationThrottling=false, bulkMutationRpcTargetMs=100}, callOptionsConfig=CallOptionsConfig{useTimeout=false, sh
ortRpcTimeoutMs=60000, longRpcTimeoutMs=600000}, usePlaintextNegotiation=false, useCachedDataPool=false}.
2019-03-21 11:08:44,490 INFO  OAuthCredentialsCache (Logger.java:info(89)) - Refreshing the OAuth token
2019-03-21 11:08:44,668 ERROR EmailToClinkExpander (EmailToClinkExpander.java:apply(109)) - Error
java.lang.IllegalStateException: Could not find an appropriate constructor for com.google.cloud.bigtable.hbase1_x.BigtableConnection
	at com.google.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:183)
	at com.liveramp.ingestion.eu_bigtable.BigtableHelper.connect(BigtableHelper.java:54)
	at com.liveramp.ingestion.eu_bigtable.BigtableHelper.getConnection(BigtableHelper.java:64)
	at com.liveramp.ingestion.eu_bigtable.BigtableHelper.get(BigtableHelper.java:71)
	at com.liveramp.ingestion.accessor.BigtableEuExpansionClient.getUKPartialClinksSet(BigtableEuExpansionClient.java:57)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.liveramp.ingestion.accessor.BigtableEuExpansionClient.getClinks(BigtableEuExpansionClient.java:72)
	at com.liveramp.ingestion.accessor.BigtableEuExpansionClient.getUkClinks(BigtableEuExpansionClient.java:86)
	at com.liveramp.ingestion.identity.expander.EmailToClinkExpander.lambda$apply$1(EmailToClinkExpander.java:96)
	at java.util.Optional.map(Optional.java:215)
	at com.liveramp.ingestion.identity.expander.EmailToClinkExpander.apply(EmailToClinkExpander.java:96)
	at com.liveramp.ingestion.identity.expander.EmailToClinkExpander.apply(EmailToClinkExpander.java:38)
	at com.liveramp.ingestion.identity.expander.RecordIdentifierExpander.apply(RecordIdentifierExpander.java:34)
	at com.liveramp.ingestion.abilitec.ClinkAppenderBatchFunction.apply(ClinkAppenderBatchFunction.java:130)
:[2]+  Stopped                    less file-processor-joblet--666.log
```

Anyone can help me, thank you very much...

**Comment by sduskis** [comment]
Can you see if there's more in the log?  Usually, there's a Caused By that's has more details about the actual problem.

**Comment by yyl719133368** [comment]
Using this code to create connection.
```      
 Configuration config = BigtableConfiguration.configure(PROJECT_ID, INSTANCE_ID);
 config.set(BigtableOptionsFactory.APP_PROFILE_ID_KEY, INSTANCE_ID);
 connection = ConnectionFactory.createConnection(config);
```
