### ISSUE TITLE
Do not use URLFetch for Credentials on GAE 8

### ISSUE THREAD

**Issue by janhicken** [googleapis/cloud-bigtable-client#2135]
Hi,

the changes introduced with 82f3a074c9a543d1bd0fa00167694b7a543974ea result in a problem with application default credentials on Google App Engine Standard Java 8: The compute engine credential mechanism does not work with URLFetch, the debugging output of `ComputeEngineCredentials` shows the following stacktrace:

```
com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine: Encountered an unexpected exception when determining if we are running on Google Compute Engine. (ComputeEngineCredentials.java:225) 
java.io.IOException: 
  at com.google.appengine.api.urlfetch.URLFetchServiceImpl.convertApplicationException(URLFetchServiceImpl.java:185) 
  at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:45)     
  at com.google.api.client.extensions.appengine.http.UrlFetchRequest.execute(UrlFetchRequest.java:74) 
  at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981) 
  at com.google.auth.oauth2.ComputeEngineCredentials.runningOnComputeEngine(ComputeEngineCredentials.java:213) 
  at com.google.auth.oauth2.DefaultCredentialsProvider.tryGetComputeCredentials(DefaultCredentialsProvider.java:292) 
  at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentialsUnsynchronized(DefaultCredentialsProvider.java:208) 
  at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:125) 
  at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:127)   
  at com.google.cloud.bigtable.config.CredentialFactory.getApplicationDefaultCredential(CredentialFactory.java:224) 
  at com.google.cloud.bigtable.config.CredentialFactory.getCredentials(CredentialFactory.java:132) 
  at com.google.cloud.bigtable.grpc.io.CredentialInterceptorCache.getCredentialsInterceptor(CredentialInterceptorCache.java:99) 
  at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:215) 
  at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:143) 
  at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:110) 
  at com.google.cloud.bigtable.hbase2_x.BigtableConnection.<init>(BigtableConnection.java:53) 
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
  at com.google.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:180) 
  at com.google.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:156)
```

This could be fixed easily by picking the `NetHttpTransport` for GAE 8 Standard [here](https://github.com/sduskis/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/config/CredentialFactory.java#L101).

A client-side workaround could be:
```java
CredentialFactory.setHttpTransportFactory(() -> new NetHttpTransport())
```

**Comment by sduskis** [comment]
AppEngine + Java 7 is no longer a thing.  The client should always use a `NetHttpTransport`.
