### ISSUE TITLE
Scans and timeouts

### ISSUE THREAD

**Issue by srwilson** [googleapis/cloud-bigtable-client#2156]
We have enabled our client to use the timeout feature. We have set a timeout of 15 seconds for both long and short rpc values since that works well for our standard Get and Put calls and our overall application level timeouts. We have noticed some unexpected behavior for our long running scans. We can demonstrate with this code
```
            Scan scan = new Scan();
            try (HTableInterface table = connection.getTable(table);
                 ResultScanner scanner = table.getScanner(scan)) {

                for (Result r : scanner) {
                    Thread.sleep(100);
                }
            }
```
After 15 seconds we see a `Could not complete RPC. Failure #0, got: Status{code=DEADLINE_EXCEEDED,` exception log message. After reading more entries and exhausting the current entries in the underly ResponseQueueReader, we see an exception is thrown. 
```
Exception in thread "main" java.lang.RuntimeException: com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
Caused by: com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.scanner.ResultQueueEntry$ExceptionResultQueueEntry.getResponseOrThrow(ResultQueueEntry.java:100)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNextMergedRow(ResponseQueueReader.java:105)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNextMergedRow(ResponseQueueReader.java:111)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:78)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:35)
	at com.google.cloud.bigtable.hbase.adapters.read.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:66)
	at com.sift.db.bigtable.BigtableScanner$1.hasNext(BigtableScanner.java:66)
	... 1 more
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 14934826494ns
	at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:517)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.onError(AbstractRetryingOperation.java:206)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.onClose(AbstractRetryingOperation.java:171)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.scanner.RetryingReadRowsOperation.onClose(RetryingReadRowsOperation.java:176)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel$2.onClose(ChannelPool.java:210)
	at com.google.bigtable.repackaged.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at com.google.bigtable.repackaged.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at com.google.bigtable.repackaged.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.io.Watchdog$WatchedCall$1.onClose(Watchdog.java:176)
...
```
It appears a user cannot iterate through the ResultScanner object for longer than the long rpc timeout value.

The behavior I would except is have the timeout on the individual ReadRows calls to get the next batch of rows. If one of those is over the timeout, then throw an exception. But reading the results of a scan can continue over the 15 second threshold. Is there a fix that can be made to implement this behavior?

It appears the scan operation will use long rpc timeout value. We don't want to raise this value because it's also used for put(Put[]) requests which we would like to keep within 15 seconds.

cc @dmwaura

**Comment by srwilson** [comment]
After digging a bit more into the HBase implementation of timeouts, I think this behavior probably makes sense. The one ask would be to be able to specify different timeout values for MutateRows and Scans. Currently they both seem to use the "Long RPC Timeout" value.
